### ISSUE TITLE
Create simple shell scripts in order to compile the code

### ISSUE THREAD

**Issue by N3v1** [heisenborn22/C-HESS#1]
@hsnborn22 I saw in your README that the user has to write long terminal commands. Wouldn‘t it be better if there‘s a simple script the user has to run in order to compile the code and run the compiled executable. 

I can try writing a shell script for that. Could you please assign this issue to me?

Best regards
NH

**Comment by N3v1** [comment]
Can I execute your chess program using macOS Sonoma and the lastest version of gcc/g++ clang compiler and CommandLineTools? Or does it only run on windows?

**Comment by hsnborn22** [comment]
The long compilation line is there just in case makefile doesn't work, but I already included a makefile to compile everything automatically. The user just needs to type "make" in the directory to compile the code. 
Also yes you can run it on macOS with gcc.
Thanks for your interest, if you find any other bugs while testing the app don't hesitate to open another issue.
Best regards
